Create a 1D NumPy array containing numbers from 0 to 9.



In [4]:
import numpy as np
array_1d = np.arange(10)

array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

🌟 Exercise 2 : Type Conversion and Array Operations


In [5]:
list1 = [3.14, 2.17, 0, 1, 2]
type(list1)

list

In [7]:
converted_array = np.array(list1, dtype=np.int64)
converted_array

array([3, 2, 0, 1, 2])

🌟 Exercise 3 : Working with Multi-Dimensional Arrays

Create a 3x3 NumPy array with values ranging from 1 to 9.



In [9]:
array_3 = np.array([1,2,3,4,5,6,7,8,9])

reshape_array_3 = array_3.reshape(3,3)
reshape_array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

Create a 2D NumPy array of shape (4, 5) filled with random numbers.



In [11]:
array_2d = np.random.random((4,5))
array_2d

array([[0.91492972, 0.61732252, 0.84444818, 0.65596703, 0.30693151],
       [0.85256867, 0.06576226, 0.47911613, 0.06490831, 0.80073772],
       [0.00173164, 0.78488293, 0.06192348, 0.62595244, 0.71027755],
       [0.37486956, 0.21118997, 0.71280805, 0.22123772, 0.1603214 ]])

🌟 Exercise 5 : Indexing Arrays

Instructions

Select the second row from a given 2D NumPy array.

In [ ]:
second_row = array_2d[1] #uses the above variable
second_row

array([0.85256867, 0.06576226, 0.47911613, 0.06490831, 0.80073772])

🌟 Exercise 6 : Reversing elements

Instructions

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [17]:
reverse_array = array_1d[::-1]
reverse_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

🌟 Exercise 7 : Identity Matrix

Instructions

Create a 4x4 identity matrix using NumPy.

In [20]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

🌟 Exercise 8 : Simple Aggregate Funcs

Instructions

Find the sum and average of a given 1D array.

In [24]:
sum_array = np.sum(array_2d)
sum_array
print(f"Sum of all elements in the array: {sum_array}")
avg_array = np.mean(array_2d)
avg_array
print(f"Average of all elements in the array: {avg_array}")

Sum of all elements in the array: 9.467886806353226
Average of all elements in the array: 0.4733943403176613


🌟 Exercise 9 : Create Array and Change its Structure

Instructions

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [32]:
array_to20 = np.arange(1, 21)
array_4x5 = array_to20.reshape(4,5)

print(array_to20)
print(array_4x5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


🌟 Exercise 10 : Conditional Selection of Values

Instructions

Extract all odd numbers from a given NumPy array.

In [34]:
example_array = np.arange(1,10)
odd_numbers = example_array[example_array % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]
